# Site settings
title: Kayla Ochoa 
header-img: img/home-bg.png
email: ochoa.kayla@yahoo.com
copyright_name: kochoa76
description: > # this means to ignore newlines until "baseurl:"
  https://github.com/kochoa76
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kochoa76
learn_profile: kochoa76
email_username: ochoa.kayla@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
